### ISSUE TITLE
拉取源码进行本地build报错

### ISSUE THREAD

**Issue by codingCenterFar** [red-axe/am-editor#266]
**问题**
拉取源码进行本地build报错
Argument of type 'Node | (() => Node | null)' is not assignable to parameter of type 'Selector'.
  Type '() => Node | null' is not assignable to type 'Selector'
**个人想法**
是不是typescript的版本问题，我看作者的源码中没有相关的lock文件，所以能否提供lock文件

**Comment by yanmao-cc** [comment]
能否给出哪一行？typescript 版本4.5

**Comment by codingCenterFar** [comment]
@aomao/engine: Clean dist directory
@aomao/engine: Build cjs with rollup
×  error     Error: D:/code/sourceCode/am-editor--aomao-engine-2.9.45/packages/engine/src/editor.ts(93,7): semantic error TS2349: This expression is not callable.
  Not all constituents of type 'Node | (() => Node | null)' are callable.
    Type 'Node' has no call signatures.
    at error (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:5253:30)
    at throwPluginError (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:17926:12)
    at Object.error (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:18533:24)
    at Object.error (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:18095:38)
    at RollupContext.error (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:38:18)
    at D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
    at Array.forEach (<anonymous>)
    at printDiagnostics (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:14)
    at Object.transform (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup-plugin-typescript2\src\index.ts:226:5)
    at D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:18734:25

**Comment by yanmao-cc** [comment]
看着好奇怪，我这儿没问题。是不是因为我这里装的全局的typescript库的原因------------------------------------------------------------------
***@***.***>
日　期：2022年10月18日 18:39:29
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] 拉取源码进行本地build报错 (Issue #266)

@aomao/engine: Clean dist directory
 @aomao/engine: Build cjs with rollup
 × error Error: D:/code/sourceCode/am-editor--aomao-engine-2.9.45/packages/engine/src/editor.ts(93,7): semantic error TS2349: This expression is not callable.
 Not all constituents of type 'Node | (() => Node | null)' are callable.
 Type 'Node' has no call signatures.
 at error (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:5253:30)
 at throwPluginError (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:17926:12)
 at Object.error (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:18533:24)
 at Object.error (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:18095:38)
 at RollupContext.error (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:38:18)
 at D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
 at Array.forEach ()
 at printDiagnostics (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:14)
 at Object.transform (D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup-plugin-typescript2\src\index.ts:226:5)
 at D:\code\sourceCode\am-editor--aomao-engine-2.9.45\node_modules\rollup\dist\shared\rollup.js:18734:25

**Comment by codingCenterFar** [comment]
非常感谢这么快速的回复，方便提供的lock文件吗？我这边全局安装4.5的版本后还是有相关问题存在

**Comment by yanmao-cc** [comment]
我删掉 lock 文件试了一下，好像所有的 `N | (() => N | null)` 这类的类型都会报错了，不知道哪里的问题

**Comment by yanmao-cc** [comment]
我把 lock 文件传到仓库了

**Comment by codingCenterFar** [comment]
好的，十分感谢～
