### ISSUE TITLE
API SSR服务启动不起来 版本v2.9.45

### ISSUE THREAD

**Issue by 1131292790** [red-axe/am-editor#268]
2022-10-30 11:30:10,253 ERROR 23209 [-/127.0.0.1/-/268ms GET /] [SSR ERROR] 渲染报错，切换至客户端渲染 ReferenceError: window is not defined
    at Module../packages/engine/src/utils/user-agent.ts (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:481567:67)
    at __webpack_require__ (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:21:30)
    at Module../packages/engine/src/utils/string.ts (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:481034:69)
    at __webpack_require__ (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:21:30)
    at Module../packages/engine/src/utils/index.ts (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:480726:65)
    at __webpack_require__ (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:21:30)
    at Module../packages/engine/src/range.ts (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:474778:64)
    at __webpack_require__ (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:21:30)
    at Module../packages/engine/src/change/dragover/index.ts (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:455291:64)
    at __webpack_require__ (/Users/wangpeixin/Downloads/am-editor--aomao-engine-2.9.25/docs-dist/umi.server.js:21:30) /

**Comment by yanmao-cc** [comment]
因为服务端没有 window 对象，所以不支持服务端渲染！

**Comment by 1131292790** [comment]
那要跑起来的话，请问下需要如何实现呢
