### ISSUE TITLE
点击表格的滚动条出现异常报错

### ISSUE THREAD

**Issue by Emma-Alpha** [red-axe/am-editor#303]
index.esm.js:29911 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Scrollbar._this.getEventClientOffset (index.esm.js:29911:1)
    at Scrollbar._this.scrollXStart (index.esm.js:29992:1)

环境：antd5  React 18

**Comment by big-camel** [comment]
有简单的复现仓库吗？

**Comment by Emma-Alpha** [comment]
找到原因了，是微前端window对象被继承了，关闭微前端的sanbox就可以了(Garfish)
